version: '3.7'

services:
  server:
    build:
      context: ./backendvehicles
      dockerfile: Dockerfile
    volumes:
      - ./backendvehicles/:/backendvehicles/
      - /var/run/docker.sock:/var/run/docker.sock
    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8001
    env_file:
      - ./backendvehicles/.env
    ports:
      - 8001:8001
    depends_on:
      - db

  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backendvehicles/.env
    expose:
      - "5433"
    ports:
      - 5433:5433
    command: -p 5433

volumes:
    postgres_data:
